window.CENTRAL_FIREBASE_CONFIG = {
  apiKey: "COLE_API_KEY_AQUI",
  authDomain: "COLE_AUTH_DOMAIN_AQUI",
  projectId: "COLE_PROJECT_ID_AQUI",
  storageBucket: "COLE_STORAGE_BUCKET_AQUI",
  messagingSenderId: "COLE_MESSAGING_SENDER_ID_AQUI",
  appId: "COLE_APP_ID_AQUI"
};

window.CENTRAL_APP_CHECK_SITE_KEY = "";
